simplify

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,45 +7,24 @@ indent() {
 echo "-----> Install Caddy"
 
 BUILD_DIR=$1
-CACHE_DIR=$2
-VENDOR_DIR="$BUILD_DIR/vendor"
-INSTALL_DIR="$VENDOR_DIR/caddy"
-CACHE_FILE="$CACHE_DIR/caddy"
-CADDY_EXTRACT_DIR="$INSTALL_DIR/extract"
 
-if [ ! -f $CACHE_FILE ]; then
-  # Install caddy
-  CADDY_REPO="${CADDY_REPO:-mholt/caddy}"
-  CADDY_VERSION="${CADDY_VERSION:-0.9.4}"
-  CADDY_FILE="caddy_linux_amd64"
-  CADDY_ARCHIVE="$CADDY_FILE.tar.gz"
-  CADDY_URL="https://github.com/$CADDY_REPO/releases/download/v$CADDY_VERSION/$CADDY_ARCHIVE"
+# Install caddy
+CADDY_REPO="${CADDY_REPO:-mholt/caddy}"
+CADDY_VERSION="${CADDY_VERSION:-0.9.4}"
+CADDY_FILE="caddy_linux_amd64"
+CADDY_ARCHIVE="$CADDY_FILE.tar.gz"
+CADDY_URL="https://github.com/$CADDY_REPO/releases/download/v$CADDY_VERSION/$CADDY_ARCHIVE"
 
-  echo "-----> Downloading Caddy"
-  wget $CADDY_URL -P $BUILD_DIR | indent
+echo "-----> Downloading Caddy"
+wget $CADDY_URL -P $BUILD_DIR | indent
 
-  echo "-----> Extracting Caddy"
-  if [ ! -f $BUILD_DIR/$CADDY_ARCHIVE ]; then
-    echo "Error: Unable to download Caddy" | indent
-    ls $BUILD_DIR | indent
-    exit 1;
-  fi
-  mkdir -p $CADDY_EXTRACT_DIR
-  tar xvf $BUILD_DIR/$CADDY_ARCHIVE -C $CADDY_EXTRACT_DIR | indent
-
-  echo "-----> Caching Caddy"
-  mkdir -p $CACHE_DIR
-  mv $CADDY_EXTRACT_DIR/$CADDY_FILE $CACHE_FILE
-#   rm -rf $CADDY_EXTRACT_DIR
-else
-  echo "-----> Using cached copy of Caddy"
+echo "-----> Extracting Caddy"
+if [ ! -f $BUILD_DIR/$CADDY_ARCHIVE ]; then
+  echo "Error: Unable to download Caddy" | indent
+  ls $BUILD_DIR | indent
+  exit 1;
 fi
+tar xvf $BUILD_DIR/$CADDY_ARCHIVE -C $BUILD_DIR | indent
 
-mkdir -p $INSTALL_DIR
-cp $CACHE_FILE $INSTALL_DIR
-
-echo "-----> Updating environment variables"
-PROFILE_PATH="$BUILD_DIR/.profile.d/caddy.sh"
-ACTUAL_INSTALL_PATH="$HOME/vendor/caddy"
-mkdir -p $(dirname $PROFILE_PATH)
-echo "export PATH=$ACTUAL_INSTALL_PATH:\$PATH" >> $PROFILE_PATH
+echo "-----> Renaming Caddy"
+mv $BUILD_DIR/$CADDY_FILE "$BUILD_DIR/caddy"
